#ifndef CONVERTER_ERRORS_H
#define CONVERTER_ERRORS_H

enum Errors {
    INCOR_ARGS_NUM,
    INCOR_METHOD_NUM,
    OPEN_INPUT_FILE,
    READ_INPUT_FILE,
    OPEN_OUTPUT_FILE,
    WRITE_OUTPUT_FILE,
    ARGS_PARSER
};

#endif //CONVERTER_ERRORS_H
