name: Simple compilation

on:
  push:
  workflow_dispatch:
  pull_request:
    branches: 
    - master 

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        cc: [gcc, clang]
        include:
          - cc: gcc
            cxx: g++
          - cc: clang
            cxx: clang++

    steps:
    - uses: actions/checkout@v2

    - name: Configure
      run: CC=${{ matrix.cc }} CXX=${{ matrix.cxx }} cmake -G"Unix Makefiles" -Bbuild

    - name: Build
      run: cmake --build build
